

module AbsPascalis where

-- Haskell module generated by the BNF converter




newtype Ident = Ident String deriving (Eq, Ord, Show, Read)
data Program = Prog Ident [Decl] [Stm]
  deriving (Eq, Ord, Show, Read)

data Decl = DVar Ident Type
  deriving (Eq, Ord, Show, Read)

data Stm
    = Skip
    | SPrint Exp
    | SDecl Decl
    | SExp Exp
    | SBlock [Stm]
    | SWhile Exp Stm
    | SReturn Exp
  deriving (Eq, Ord, Show, Read)

data Exp
    = EAss Ident Exp
    | ELt Exp Exp
    | EAdd Exp Exp
    | ESub Exp Exp
    | EMul Exp Exp
    | Call Ident [Exp]
    | EVar Ident
    | EStr String
    | EInt Integer
    | EDouble Double
  deriving (Eq, Ord, Show, Read)

data Type = TInt
  deriving (Eq, Ord, Show, Read)

