

module AbsPascalis where
import Data.Array
import qualified Data.Map as M
type ArrII = Array Int Int
type EExp = Exp
type Var = String
type Loc = Int
type Env = M.Map Ident Loc
type Store = M.Map Loc (Type, EExp)


-- Haskell module generated by the BNF converter




newtype Ident = Ident String deriving (Eq, Ord, Show, Read)
data Program = Prog Ident [Decl] [Stm]
  deriving (Eq, Ord, Show, Read)

data Decl
    = DVar Ident Type
    | DParam Ident Type
    | DAVar Ident Exp Exp Type
    | DAPVar Ident Type Type
    | DProc Ident [Decl] [Decl] [Stm]
    | DFunc Ident [Decl] Type [Decl] [Stm]
  deriving (Eq, Ord, Show, Read)

data Stm
    = Skip
    | SIf Exp Stm
    | SIfElse Exp Stm Stm
    | SExp Exp
    | SDecl [Decl]
    | SBlock [Stm]
    | SReturn Exp
    | STSet Ident Exp Exp
    | SSet Ident Exp
    | SWhile Exp Stm
    | SFor Ident Exp Exp Stm
  deriving (Eq, Ord, Show, Read)

data Exp
    = BTrue
    | BFalse
    | Null
    | BNot Exp
    | EFSub Exp
    | ELSub Exp Exp
    | ERSub Exp Exp
    | ELRSub Exp Exp Exp
    | EKey Exp Exp
    | EOr Exp Exp
    | EAnd Exp Exp
    | EAss Exp Exp
    | ENAss Exp Exp
    | ELt Exp Exp
    | EGt Exp Exp
    | ELEt Exp Exp
    | EGEt Exp Exp
    | EAdd Exp Exp
    | ESub Exp Exp
    | EMul Exp Exp
    | EDiv Exp Exp
    | Call Ident [Exp]
    | EStr String
    | EChar Char
    | EVar Ident
    | EInt Integer
    | EArrII ArrII
    | EOrd Exp
    | ELen Exp
    | EProc [Decl] [Stm] Env
    | EFunc [Decl] Type [Stm] Env

    | EDouble Double
  deriving (Eq, Ord, Show, Read)

data Type
    = TInt
    | TBool
    | TStr
    | TChar
    | TFunc
    | TProc
    | TArr Type Type
    | TDict Type Type
  deriving (Eq, Ord, Show, Read)

